export const dataInit={
    login: "name",
    id: 1,
    node_id: "MDQ6VXNlcjIwNzM1NTkx",
    avatar_url: "https://pbs.twimg.com/media/EmUM83TXIAAss5k.png",
    gravatar_id: "",
    url: "https://github.com/",
    html_url: "https://github.com",
    followers_url: "https://github.com",
    following_url: "https://github.com",
    gists_url: "https://github.com",
    starred_url: "https://github.com",
    subscriptions_url: "https://github.com",
    organizations_url: "https://github.com",
    repos_url: "https://github.com",
    events_url: "https://github.com",
    received_events_url: "https://github.com",
    type: "User",
    site_admin: false,
    name: "nameuser",
    company: null,
    blog: "",
    location: "location",
    email: null,
    hireable: null,
    bio: "bio ",
    twitter_username: null,
    public_repos: 0,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "created_at",
    updated_at: "updated_at"
    }